const BaseUrl = ''
export const ADD_ENTITY = BaseUrl + '/api/entity'
export const GET_ENTITY_LIST = BaseUrl + '/api/entity/list'
export const ADD_PROJECT = BaseUrl + '/api/project'
export const SEARCH_PROJECT = BaseUrl + '/api/project/search'
export const ADD_INSPECTION = BaseUrl + '/api/inspection'
export const SEARCH_INSPECTION = BaseUrl + '/api/inspection/search'

export const ADD_PRINCIPAL = BaseUrl + '/api/principal'
export const SEARCH_PRINCIPAL = BaseUrl + '/api/principal/search'
export const GET_ENTRY_BY_ORDERID = BaseUrl + '/api/entry'
export const FIND_USER = BaseUrl + '/api/user'
export const SEARCH_ENTITY = BaseUrl + '/api/entity/search'

export const SAVE_ENTRY = BaseUrl + '/api/entry'
export const ADD_ENTRIES = BaseUrl + '/api/entries'
export const GET_ENTRIES = BaseUrl + '/api/entries'
export const REMOVE_ENTRY = BaseUrl + '/api/entry/remove'

export const ADD_RECORD = BaseUrl + '/api/record'
export const QUERY_RECORDS = BaseUrl + '/api/records'
export const QUERY_RECORD = BaseUrl + '/api/record/query'
