export const SET_TOKEN = 'SET_TOKEN'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_RECORDS = 'SET_RECORDS'
export const SET_RECORD = 'SET_RECORD'
export const SET_SEARCHINPUT = 'SET_SEARCHINPUT'
export const SET_INSPECTIONS = 'SET_INSPECTIONS'

export const SET_PRINCIPALS = 'SET_PRINCIPALS'

export const SET_PROJECTS = 'SET_PROJECTS'

export const SET_ENTITIES = 'SET_ENTITIES'
export const SET_OWNERS = 'SET_OWNERS'
export const SET_DESIGNERS = 'SET_DESIGNERS'
export const SET_BUILDERS = 'SET_BUILDERS'
export const SET_SUPERVISORS = 'SET_SUPERVISORS'

export const SET_ENTRIES = 'SET_ENTRIES'

export const SET_PROJECT_ENTITY = 'SET_PROJECT_ENTITY'
